---
title: "Development of a German Instrument for Self-Rated Data Literacy"
author: "Leonie Hagitte"
date: "`r Sys.Date()`"
output:
  pdf_document:
    includes:
      in_header: "preamble.tex" 
header-includes:
 header-includes:
  - \setlength{\parindent}{0.5in}  # Indent the first line by 0.5 inches
  - \setlength{\parskip}{0pt}      # Disable space between paragraphs
  - \usepackage{sectsty}            # Use the sectsty package
  - \sectionfont{\centering\bfseries\LARGE}  # Center and bold level 1 headers
  - \subsectionfont{\bfseries\large}        # Bold and large for level 2 headers
  - \subsubsectionfont{\bfseries\itshape\large}  # Bold and italic for level 3 headers
site: bookdown::bookdown_site
documentclass: article
bibliography:
  - packages.bib
  - literature.bib
csl: apa7.csl
link-citations: true
description: ''
fontsize: 12pt
linestretch: 1.2
geometry: left=3.9cm, right=3.3cm, top=2.5cm, bottom=3cm
papersize: a4
classoption: twoside
repro:
  packages:
    - devtools
    - here
    - aaronpeikert/repro@adb5fa56
    - bookdown
    - usethis
    - gert
subtitle: "An Algorithm-based Approach to Scale Development"
---

\newpage\null\thispagestyle{empty}\newpage

```{r, include=FALSE}
knitr::opts_chunk$set(
  comment = ">"
)
```

# Abstract {-}

```{r child='abstract.Rmd'}
```
