# Supplementary Material

\begin{table}
\begin{flushleft}
\caption{The selected item pool}
\begin{tabular}{lp{17cm}}
\toprule
Factor & Item \\
\midrule
1 & Bei der Auswertung von Grafiken bin ich in der Lage, Widersprüche zu erkennen. \\
1 & Ich erkenne, ob die Interpretationen Anderer zu den vorliegenden Daten passen. \\
1 & Ich kenne unterschiedliche Arten von Grafiken. \\
1 & Ich kann die zentrale These eines wissenschaftlichen Textes erkennen.\\
2 & Wenn Ich die Glaubwürdigkeit von Informationen beurteile, berücksichtige ich den Ruf der Quelle.\\
2 & Ich kenne Merkmale zur Bewertung von Datenqualität.\\
2 & Ich überprüfe die Qualifikation von Autor*innen, bevor ich mich auf die Informationen verlasse.\\
2 & Ich erkenne, wenn Daten schlechte Qualität haben.\\
3 &  Ich beschäftige mich mit Informationen, die meine Ansichten in Frage stellen.\\
3 &  Ich kann schnell und ohne Schwierigkeiten Informationen in Datenbanken finden.\\
3 &  Ich bevorzuge datengestützte Informationen, wenn ich mir eine Meinung bilde.\\
3 &  Ich kann neue Informationen in meinen Wissensstand integrieren.\\
4 &  Ich kann Ergebnisse in Streudiagrammen darstellen.\\
4 &  Ich kann Daten in Grafiken so präsentieren, dass sie für verschiedene Zielgruppen verständlich sind.\\
4 &  Ich kann aus verschiedenen Darstellungsformen, die am besten geeignete auswählen.\\
4 &  Ich kann mit Programmen Grafiken erstellen, um Ergebnisse zu präsentieren.\\
5 &  Ich bin in der Lage, einfache Datenbanken zu verwalten.\\
5 &  Ich kann Datensätze mit einfachen statistischen Methoden analysieren.\\
5 &  Wenn ich mit umfangreichen Datensätzen konfrontiert werde, kann ich daraus Erkenntnisse gewinnen.\\
5 &  Wenn ich Daten analysiere, achte ich auf ein systematisches Vorgehen.\\

\bottomrule
\end{tabular}

\bigskip
\small\textit{Note}. The items selected by the algorithm in German.
\end{flushleft}
\end{table}


\begin{table}[!htbp]
\centering
\rotatebox{90}{%
\begin{minipage}{\textheight}
\caption{Correlations of Residuals}
\scriptsize % This makes the font smaller
\begin{tabular}{lcccccccccccccccccccc}
\hline
\textbf{Item} & \textbf{F1F6} & \textbf{F1F8} & \textbf{F1F11} & \textbf{F1F14} & \textbf{F2F2} & \textbf{F2F6} & \textbf{F2F15} & \textbf{F2F20} & \textbf{F3F2} & \textbf{F3F4} & \textbf{F3F6} & \textbf{F3F9} & \textbf{F4F1} & \textbf{F4F3} & \textbf{F4F6} & \textbf{F4F8} & \textbf{F5F3} & \textbf{F5F4} & \textbf{F5F8}  \\ 
\hline
F1F6    & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F8    & -0.342 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F11   & -0.118 & 0.497 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F14   & 0.231  & -0.287 & -0.010 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F2    & 0.225  & 0.115  & 0.127  & -0.203 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F6    & -0.396 & 0.141  & 0.363  & 0.010  & -0.078 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F15   & -0.444 & 0.258  & 0.174  & -0.041 & -0.264 & 0.160  & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F20   & -0.015 & -0.193 & -0.269 & 0.223  & -0.349 & -0.029 & -0.208 & 1.000 &       &       &       &       &       &       &       &       &       &       &       \\
F3F2    & 0.314  & -0.144 & -0.043 & 0.005  & -0.002 & -0.403 & -0.170 & 0.307  & 1.000 &       &       &       &       &       &       &       &       &       &       \\
F3F4    & 0.127  & 0.040  & 0.153  & 0.089  & 0.253  & -0.266 & -0.357 & -0.092 & 0.008  & 1.000 &       &       &       &       &       &       &       &       &       \\
F3F6    & 0.223  & 0.017  & -0.106 & 0.296  & 0.135  & -0.447 & 0.332  & 0.063  & 0.079  & 0.177  & 1.000 &       &       &       &       &       &       &       &       \\
F3F9    & 0.117  & -0.037 & -0.169 & 0.409  & -0.206 & -0.284 & -0.073 & 0.246  & 0.324  & 0.239  & 0.066  & 1.000 &       &       &       &       &       &       &       &       \\
F4F1    & -0.030 & 0.026  & -0.345 & -0.153 & -0.282 & -0.053 & 0.001  & 0.064  & -0.051 & -0.300 & -0.237 & 0.154  & 1.000 &       &       &       &       &       &       &       \\
F4F3    & -0.079 & -0.381 & -0.184 & 0.439  & -0.208 & 0.170  & -0.273 & 0.591  & 0.215  & 0.154  & -0.239 & 0.398  & -0.214 & 1.000 &       &       &       &       &       &       \\
F4F6    & 0.004  & 0.397  & -0.102 & -0.234 & 0.146  & -0.199 & 0.322  & -0.080 & 0.175  & -0.168 & -0.005 & 0.095  & 0.128  & -0.057 & 1.000 &       &       &       &       &       \\
F4F8    & 0.164  & -0.038 & -0.079 & 0.256  & -0.021 & 0.005  & -0.061 & -0.035 & 0.086  & -0.146 & 0.136  & -0.161 & -0.221 & -0.171 & -0.129 & 1.000 &       &       &       &       \\
F5F3    & 0.461  & -0.275 & -0.141 & 0.259  & 0.065  & -0.448 & -0.248 & -0.397 & -0.159 & 0.150  & -0.012 & -0.007 & 0.169  & -0.253 & 0.105  & 0.165  & 1.000 &       &       &       \\
F5F4    & -0.085 & 0.089  & -0.192 & 0.052  & -0.203 & 0.003  & -0.417 & 0.110  & 0.130  & -0.005 & -0.312 & 0.291  & 0.398  & 0.115  & -0.136 & -0.051 & -0.032 & 1.000 &       &       \\
F5F8    & 0.017  & -0.330 & -0.193 & -0.111 & 0.043  & -0.396 & -0.149 & -0.095 & 0.253  & 0.055  & -0.189 & 0.179  & 0.049  & 0.146  & 0.205  & -0.184 & 0.334  & 0.247  & 1.000 &       \\
F5F18   & 0.076  & 0.138  & 0.136  & 0.118  & -0.094 & -0.245 & -0.009 & -0.075 & 0.224  & 0.010  & 0.045  & 0.308  & -0.217 & -0.181 & 0.069  & 0.468  & 0.264  & -0.028 & 0.032  & 1.000 \\
\hline

\end{tabular}
\par % Ensures separation of the table and note

\small Note. The table displays the lower half of the correlation matrix of the items residuals from the training sample.
\end{minipage}%
}
\end{table}


\begin{table}[!htbp]
\centering
\rotatebox{90}{%
\begin{minipage}{\textheight}
\caption{Correlations of Residuals}
\scriptsize % This makes the font smaller
\begin{tabular}{lcccccccccccccccccccc}
\hline
\textbf{Item} & \textbf{F1F6} & \textbf{F1F8} & \textbf{F1F11} & \textbf{F1F14} & \textbf{F2F2} & \textbf{F2F6} & \textbf{F2F15} & \textbf{F2F20} & \textbf{F3F2} & \textbf{F3F4} & \textbf{F3F6} & \textbf{F3F9} & \textbf{F4F1} & \textbf{F4F3} & \textbf{F4F6} & \textbf{F4F8} & \textbf{F5F3} & \textbf{F5F4} & \textbf{F5F8} \\ 
\hline
F1F6     & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F8     & 0.235 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F11    & 0.264 & 0.124 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F14    & -0.352 & -0.083 & -0.010 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F2     & -0.056 & -0.278 & 0.045 & 0.061 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F6     & 0.005 & 0.091 & 0.266 & 0.224 & -0.568 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F15    & -0.207 & -0.310 & -0.028 & 0.031 & 0.346 & -0.491 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F20    & 0.032 & 0.067 & 0.411 & 0.103 & -0.033 & 0.120 & -0.020 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       \\
F3F2     & -0.192 & -0.306 & -0.480 & 0.176 & 0.280 & -0.306 & 0.068 & -0.107 & 1.000 &       &       &       &       &       &       &       &       &       &       &       \\
F3F4     & -0.172 & -0.096 & -0.262 & 0.107 & -0.140 & 0.145 & 0.297 & -0.465 & 0.056 & 1.000 &       &       &       &       &       &       &       &       &       &       \\
F3F6     & 0.188 & 0.306 & 0.177 & -0.031 & 0.128 & -0.103 & 0.083 & -0.026 & -0.089 & -0.387 & 1.000 &       &       &       &       &       &       &       &       &       \\
F3F9     & 0.192 & -0.198 & 0.250 & 0.143 & 0.145 & 0.107 & -0.117 & 0.043 & -0.163 & -0.317 & 0.492 & 1.000 &       &       &       &       &       &       &       &       \\
F4F1     & 0.110 & 0.329 & -0.152 & 0.038 & -0.287 & 0.451 & -0.323 & 0.186 & -0.368 & 0.108 & -0.155 & -0.161 & 1.000 &       &       &       &       &       &       &       \\
F4F3     & 0.057 & 0.032 & 0.427 & 0.112 & 0.077 & 0.156 & -0.237 & 0.456 & -0.524 & -0.292 & 0.010 & 0.282 & 0.262 & 1.000 &       &       &       &       &       &       \\
F4F6     & 0.017 & -0.065 & 0.188 & 0.272 & 0.366 & 0.102 & -0.352 & 0.132 & -0.052 & 0.053 & -0.257 & 0.207 & 0.093 & 0.506 & 1.000 &       &       &       &       &       \\
F4F8     & 0.091 & 0.105 & 0.256 & 0.361 & -0.429 & 0.713 & -0.308 & 0.112 & -0.396 & 0.159 & -0.114 & -0.007 & 0.461 & 0.106 & 0.092 & 1.000 &       &       &       &       \\
F5F3     & 0.092 & -0.036 & -0.462 & -0.286 & 0.037 & -0.002 & 0.106 & -0.102 & 0.017 & 0.337 & -0.293 & -0.230 & 0.244 & -0.245 & 0.046 & -0.231 & 1.000 &       &       &       \\
F5F4     & -0.089 & -0.128 & 0.293 & -0.222 & -0.329 & 0.420 & -0.225 & 0.336 & -0.486 & 0.078 & -0.265 & -0.016 & 0.293 & 0.641 & 0.255 & 0.163 & 0.043 & 1.000 &       &       \\
F5F8     & 0.278 & 0.011 & -0.143 & -0.185 & 0.275 & -0.429 & 0.071 & 0.036 & 0.229 & -0.178 & 0.321 & 0.272 & -0.064 & 0.074 & 0.156 & -0.497 & 0.016 & -0.053 & 1.000 &       \\
F5F18    & 0.312 & 0.225 & 0.078 & -0.384 & 0.119 & 0.132 & -0.284 & 0.281 & -0.166 & -0.100 & -0.103 & -0.152 & 0.466 & 0.346 & 0.249 & 0.179 & 0.173 & 0.288 & -0.038 & 1.000 \\
\hline

\end{tabular}
\par % Ensures separation of the table and note

\small Note. The table displays the lower half of the correlation matrix of the items residuals from the test sample.
\end{minipage}%
}
\end{table}
