# Background

In a world characterized by information overload and rapid technological advancements [@Koltay2017; @Leighton2021; @Roetzel2019], the relevance of data literacy for today's society becomes evident. Data literacy serves as a potent tool in navigating the complex data-driven environment [@Cui2023; @risdale2015; @Carmi2020; @Leighton2021] and individuals equipped with strong data literacy skills can discern patterns, critically evaluate information, and make informed decisions [@Chen2024; @Cui2023].
The exploration of citizens' interaction with media and the cultivation of their agency has traditionally started around concepts such as written literacy and information literacy [@ACRL2000; @brown2002]. Information literacy, as defined by the American Library Association in 1989, encompasses the skills required to locate, evaluate, and effectively use information [@brown2002]. This foundational understanding of information literacy has evolved through various frameworks and models, emphasizing its importance in educational settings and lifelong learning [@tomar2023]. In more recent discussions, data literacy has been approaching relevance among discussed competencies regarding what is necessary for agency in the current society [@Carmi2020; @Leighton2021]. Deficiency in data literacy not only exposes individuals to various risks and harms on personal, social, physical, and financial levels but also constrains their capacity to actively engage as informed citizens within an evolving, data-driven society [@Carmi2020; @Leighton2021]. Thus, data literacy is a competency that is becoming increasingly important to everyone. Research has acknowledged this in recent years, as more and more research is being done in that direction [@Cui2023; @Chen2024]. This study aims to complement the current research, with a self rating questionnaire for assessing data literacy among citizens.

Data literacy involves the ability to effectively collect, manage, evaluate, and apply data in a critical manner [@risdale2015]. According to @wolff2016, it means being able to ask and answer everyday questions using both small and large datasets while considering ethical aspects. This includes skills such as selecting, cleaning, analyzing, visualizing, criticizing, and interpreting data, as well as communicating insights from data, and using data for various purposes. @frank2016 distinguishes between cognitive skills, like data collection and analysis, and social skills, which involve trusting data while maintaining skepticism. @prado2013 outline five dimensions of data literacy: understanding data, acquiring data, interpreting and evaluating data, managing data, and using data. Understanding data includes knowing their types, roles, and significance, while acquiring data involves evaluating and selecting sources. Interpreting and evaluating data encompass understanding different presentation methods and data interpretation. Managing data includes storage, management, and reuse. Using data involves preparation, analysis, communication, and ethical considerations [@prado2013].
This small comparison already highlights one prominent attribute of data literacy: it is a heterogeneous concept [@Chen2024]. Every subject or profession seems to hold their own definition or framework of data literacy [@Chen2024; @Cui2023]. While heterogeneity is beneficial for assessing specific skills (e.g. in a recruitment test), it limits the generalisability and comparability of data literacy across individuals with different background. It furthermore limits the accuracy of communication about the topic as two people with different background might hold different definitions on data literacy. In the study from @Cui2023 it also becomes apparent, that one group seems to be less focused on in the research on data literacy: citizens or the broader public. Citizens in this case mean people of the general public, that hold no special role or profession, related to data handling or aspects related to data literacy [@wolff2016]. 
Despite being the largest demographic group, citizens are often overlooked in favor of specific professions such as researchers, librarians, students, or educators [@Cui2023]. This trend raises questions about the emphasis on certain aspects of data literacy, many of which tend to align more closely with professional roles than with the needs of laypeople [@schüller2020].
In their framework @schüller2020 highlight the different roles, people can hold: Some of the factors or skills regard *data-consumption*, whereas the most are skills *data-producers* would have. This is also reflected when taking a look into related concepts. The definition proposed by @wolff2016 suggests that data literacy shares some common competencies with statistical and information literacies.  
Information literacy, often studied in library sciences, overlaps with data literacy in terms of accessing, critically evaluating, and using data sources [@prado2013; @shields2005]. @wolff2016 also emphasize the importance of the data inquiry process, starting from identifying problems, designing studies, acquiring data, conducting analysis, to drawing data-based conclusions. In comparison, @gould2017 argued that data literacy is essentially the same as statistical literacy but with additional competencies needed due to the increasing importance of data. These added competencies include understanding who collects the data, how and why data is collected, and understanding data privacy and ownership [@gould2017]. 

Additionally, when discussing data literacy, it is essential to understand the distinctions between the terms data and information, and their relationship to one another. The concepts of data and information are foundational in various fields, yet their precise definitions and relationships are often subject to interpretation [@Koltay2017; @Schneider2013]. While data can be viewed as the raw material [@shannon1948] from which information is derived [@bates2005], it is the reduction of entropy through organization and interpretation that gives rise to meaningful information [@brillouin1953;  @jaynes1957]. Thus, rather than viewing data as synonymous with entropy or information, it is more accurate to consider information as emerging from the structured representation of data.  

It is structured representation of data, that also according to the framework of [@schüller2020], citizens are primarily concerned with: citizens hold roles where they mainly consume data or information. Consequently, they may encounter difficulties with tasks or items related to producing facets such as providing or exploiting data. This imbalance could potentially undermine the fairness of tests and questionnaires designed to assess data literacy, particularly, if these assessments prioritize competencies closer to data and statistical literacy over those closer to information literacy.

## Conceptual Integration and Delineation From Other Concepts  
Because data literacy is such a heterogeneous construct, it is very prone to construct proliferation. This, for example, becomes evident, when looking into the literature review from @Cui2023. In their study they found over fourteen different definitions of data literacy, incorporating different sets of 75 competencies. Furthermore, very few of those definitions are targeted at citizens, and none of the questionnaires they report target citizens. 
Thus, the objective of this study was to formulate a definition of data literacy, based on the current literature, that works for citizens. For the conceptual integration, I used the review of @Cui2023 and assessed what competencies were incorporated in most of the definitions, and would therefore be considered central to the construct. This included counting the same competencies as well as checking what competencies might be named differently, but are considered the same substantively. Furthermore, data literacy encompasses certain characteristics and behaviors from similar constructs. Examples for those convergent constructs are *critical thinking*, *media competency*, *technology competency*, *statistical literacy* as well as *information literacy* [@Chen2024; @Leighton2021; @Cui2023]. As those constructs share substantive parts, differing in size regarding the respective definition of the constructs, it is to be expected that all of them show moderate to strong positive correlations.
Concluding, data literacy can be defined as "the ability to collect, manage, evaluate, and apply data effectively. It involves asking and answering real-world questions from datasets while considering ethical use. Core skills include selecting, cleaning, analyzing, visualizing, presenting, critiquing, and interpreting data, information and their sources" [@Cui2023; @wolff2016; @risdale2015].

Most definitions in the literature discern about five factors of general data literacy [@Cui2023], which can be further categorized into three *consumer* and two *producer* facets [@schüller2020]. Trying to describe the associated behaviors, I labeled these five factors as *Comprehension*, *Evaluation*, *Integration*, *Communication*, and *Statistics*. The *consumer* facets: *Comprehension*, *Evaluation*, and *Integration*, are broadly relevant to nearly everyone in society, including the general public. In contrast, the *producer* facets: *Communication* and *Statistics*, are primarily important for individuals actively working with data. The *consumer* facets are closely aligned with media literacy, emphasizing critical analysis and interpretation of various media formats to support understanding and engagement with media content (cf. Table 1).    

\begin{table}[!htbp]
\centering
\caption{The Nomological Network of the Construct and its Factors}
\scriptsize
\begin{tabular}{|p{0.15\textwidth}|p{0.30\textwidth}|p{0.25\textwidth}|p{0.21\textwidth}|}
\hline
\textbf{Factor} & \textbf{Description} & \textbf{Convergent Constructs} & \textbf{Adjacent Constructs} \\
\hline
\textbf{Data Literacy} & The ability to collect, manage, evaluate, and apply data effectively. & Statistical Literacy +++

Information Literacy +++

Media Competency ++

Critical Thinking ++
& Need for Cognition +

Openness +

Conscientiousness + \\
\hline
\textbf{Comprehension} & Individuals with high scores on this factor demonstrate a strong aptitude for processing and making sense of information across different formats, enabling them to draw accurate conclusions and insights. & Statistical Literacy ++

Information Literacy +++

Media Competency ++

Critical Thinking +++
& Need for Cognition: +

Openness +

Conscientiousness +\\
\hline
\textbf{Evaluation} & Represents the ability to evaluate the credibility and reliability of information by considering the reputation of the source, the context in which it is presented, and potential biases or vested interests. Individuals high in this factor demonstrate a heightened awareness of these elements. & Statistical Literacy ++

Information Literacy +++

Media Competency +++

Critical Thinking +
& Need for Cognition: ++ 

Openness +

Conscientiousness +\\
\hline
\textbf{Integration} & Reflects the ability to seek a comprehensive understanding of diverse topics by engaging with multiple perspectives and integrating data-driven insights. Individuals high in this factor are open to adapting their opinions based on new evidence, prioritize evidence-based information, and strive to align their values with reliable data. & Statistical Literacy ++

Information Literacy ++

Media Competency ++

Critical Thinking +++ 
& Need for Cognition: ++ 

Openness ++

Conscientiousness +\\
\hline
\textbf{Communication} & Individuals scoring high in this factor hold the ability to translate data into simple visualizations, present findings confidently, and articulate complex information effectively in written and visual as well as verbal formats. & Statistical Literacy +++

Information Literacy ++

Media Competency +++

Critical Thinking ++
& Need for Cognition: +

Openness +

Conscientiousness +\\
\hline
\textbf{Statistics} & It involves proficiency in organizing and analyzing data using software tools, conducting statistical analyses, and understanding research methodologies. & Statistical Literacy +++

Information Literacy ++

Media Competency ++

Critical Thinking +
& Need for Cognition: ++ 

Openness +

Conscientiousness ++\\
\hline
\end{tabular}
\begin{flushleft}
\vspace{9pt}
\footnotesize\textit{Note}. The table illustrates the nomological network of Data Literacy and its factors. Each factor is described in terms of its primary function, along with convergent constructs and adjacent constructs. The constructs are displayed alongside their expected correlation with the data literacy factors (+++ = strong positive, ++ = moderate positive, + = weak positive).    
\end{flushleft}

\end{table}

### Consumer Facets  
The factor *Comprehension* encompasses behaviors and skills associated with critical thinking [@rear2019; @payan2022], such as identifying weaknesses in ones reasoning or actively shaping discourse and public dissemination of information. It involves the ability to comprehend various forms of data presentation, detect inconsistencies, interpret data comprehensively, and identify logical fallacies. Individuals with high scores on this factor demonstrate a strong aptitude for processing and making sense of information across different formats, enabling them to draw accurate conclusions and insights [@wolff2016; @vahey2006; @carlson2014].
It includes elements of information literacy [@ACRL2000] by focusing on evaluating the credibility of data sources, considering factors like reputation and biases, similar to assessing the quality of information sources (Evaluation & Integration) [@Webber2017]. Both statistical and information literacy involve using data, and information to make informed decisions [@Webber2017; @Gal2002; @callingham2006].
Therefore, the *Evaluation* factor involves skills related to critically evaluating information sources and discerning between facts and opinions [@gould2017; @frank2016; @callingham2006; @kouts-klemm2019]. It encompasses the ability to assess the credibility and reliability of information, considering factors such as the reputation of the source and the context in which the information was presented. Individuals scoring high on this factor demonstrate awareness of potential biases or vested interests in information sources [@lusiyana2020; @kouts-klemm2019; @callingham2006].  
Data literacy often emphasizes integrating data-driven insights into one's opinions and values, which influence decision-making processes, without focusing on the decision making [@wolff2016; @callingham2006]. Thereby it aligns with the goals of statistical and information literacy (cf. Table 1).
The *Integration* factor relates to the ability and motivation to integrate data-driven insights into one's worldview and values [@Carmi2020; @wolff2016; @callingham2006]. It involves actively seeking comprehensive understanding of various topics, engaging with diverse perspectives, and consciously incorporating data-driven insights. Individuals scoring high in this factor adapt their opinions based on new data, prefer evidence-based information, and ensure their values align with reliable data. They engage with information and perspectives that challenge their existing views, showing a willingness to reassess their opinions and positions based on new data [@Carmi2020]. 

### Producer Facets  
The *Communication* factor revolves around the often referenced skill to effectively communicate and present data through various means, including visual formats, verbal explanations, and written descriptions [@kouts-klemm2019; @prado2013; @wolff2016].
It requires translating complex data into clear formats, ensuring comprehension by varied audiences. Individuals scoring high in this factor hold the ability to translate data into simple visualizations, present findings confidently, and articulate complex information effectively in written, visual as well as verbal formats [@kouts-klemm2019; @prado2013; @wolff2016].
  
This definition, incorporates statistical literacy by emphasizing data interpretation, analysis, and understanding different types of data representations, such as graphs and tables (Statistics) [@Gal2002]. 
The *Statistics* factor covers skills related to managing and analyzing data effectively [@risdale2015; @gould2017]. It involves proficiency in organizing and analyzing data using software tools, conducting statistical analyses, and understanding research methodologies [@gould2017; @williams2014]. Individuals scoring high on this factor exhibit competence in conducting interviews or surveys for data collection, performing basic statistical analysis and recognizing trends in graphical representations [@gould2017; @williams2014; @deahl2014]. In contrast to this presented concept of the *Statistics* factor, statistical literacy often focuses more narrowly on statistical concepts and methods, such as probability, sampling, and hypothesis testing [@Gal2002; @gould2017]. The *Statistics* factor encompasses a broader range of skills beyond statistical concepts, such as data visualization, software usage, and understanding data collection methods. While information literacy involves assessing the quality of information sources, this data literacy definition places a particular emphasis on assessing data quality, considering factors like sample size, biases, and data context. This aspect extends beyond traditional information literacy [@ACRL2000] and is more specific to data literacy.  
The factors *Evaluation* and *Statistics* encompass behaviors and skills related to technology competency, including navigating and critically evaluating online sources and platforms, using information and communication technology, and utilizing statistical software. Data literacy involves proficiency in using technology, but specifically focuses on understanding and working with data. Technology competency encompasses a broader set of digital skills that extend beyond those relevant for data literacy.

## Nomological net 
The term data literacy could evoke associations with skills, abilities or knowledge.
Ability refers to an individuals potential or aptitude, encompassing innate or developed capacities across domains such as linguistic, mathematical, or motor abilities [@carroll1993].
Knowledge, by contrast, is the cognitive representation or mental model of information, objects, and relationships. It forms the informational basis for interaction with and interpretation of the environment, encompassing all stored and retrievable data within an individuals mental framework [@NormanRumelhart1975].
Skill describes the application of learned and task-specific activities, often categorized into motor, cognitive, or social domains. Unlike abilities, skills imply mastery achieved through practice and are typically assessed based on performance quality [@green1998].

Motivational theories have evolved from broad mechanistic views to more nuanced understandings that incorporate social-cognitive aspects of motivation, highlighting the interplay between personality traits and learning outcomes [@dweck1988; @mischel1973; @ross2005]. This reflects a broader trend in psychology where the understanding of learning is increasingly contextualized within the individual learners psychological profile, including their personality characteristics [@komarraju2011; @mischel1973; @elander2004].
Those constructivist theories advocate for learning as a socially mediated process, where personality traits such as openness to experience and conscientiousness can significantly influence how learners engage with content and interact with peers [@komarraju2011]. 

The role of motivation, influenced by personality traits, is particularly relevant in the context of competencies such as data literacy. Data literacy requires not only cognitive skills but also the motivation to engage with data, interpret it, and apply it effectively [@keshavarz2021]. Research indicates that individuals with high levels of conscientiousness and openness are more likely to pursue learning opportunities related to data literacy, as these traits correlate with intrinsic motivation and a proactive approach to learning [@keshavarz2021; @mahmood2021; @saleh2018]. For example, students who exhibit high conscientiousness tend to set specific learning goals and persist in their efforts to achieve them, which is essential for mastering complex skills like data analysis [@komarraju2009; @saleh2018].  
Thus, data literacy can be seen as more on the side of competences or proficiencies, because many behaviors, incorporated in data literacy go beyond the mere question of whether a person is 'able to do it'. It includes the question of one's motivation to do it. 

### Need for Cognition    
The concept of *Need for Cognition* (NFC), can be defined as "a need to structure relevant situations in meaningful, integrated ways. It is a need to understand and make reasonable the experiential world" [@cohen1955, p. 291]. The concept captures individual variations in the engagement and enjoyment of thinking tasks [@bless1994]. As data literacy incorporates several cognitive aspects as well as the motivation to understand data and information one gets presented with, it is expected to correlate positively with NFC. As NFC is more trait like and data literacy is more a competency and therefore less stable, it should not correlate too highly positive (i.e. correlation should be small) (cf. Table 1). 

### Opennes to new Experiences
*Openness to new experiences* is one factor of the *Big Five* [@costa1992] and reflects a broad appreciation for art, emotion, adventure, unconventional ideas, imagination, curiosity, and diverse experiences [@john2008]. Individuals high in openness tend to be intellectually curious, receptive to emotions, appreciative of beauty, and eager to explore new possibilities. They are often more creative and emotionally attuned compared to those low in openness. In contrast, individuals low in openness tend to seek fulfillment through perseverance and are characterized as pragmatic and sometimes viewed as dogmatic or closed-minded [@john2008]. As already mentioned, data literacy can be thought of as a competency, thus incorporating the individual motivation, leading to a certain behavior. Therefore, openness to new experiences is expected to correlate positively with data literacy. As openness to new experiences is more trait like and data literacy is not, the correlation is expected to be small (cf. Table 1). 

### Conscientiousness  
*Conscientiousness* is one factor of the *Big Five* [@costa1992] and refers to an individuals propensity for self-discipline, dutifulness, and striving for achievement in alignment with external standards or expectations. It encompasses levels of impulse control, regulation, and goal-directed behavior [@john2008, @toegel2012; @costa1992]. High conscientiousness is characterized by persistence and focus, often perceived as stubbornness, whereas low conscientiousness is linked to flexibility and spontaneity, potentially manifesting as carelessness and unreliability [@toegel2012]. Individuals with high conscientiousness tend to prefer planned actions over spontaneous ones [@costa1992; @john2008].  
The cognitive aspects of data literacy as well as the motivation to understand data and information speaks to the conscientiousness of people as well. As being critical and at times detail oriented (e.g. in interpreting results, or spotting inconsistencies in presented information or while examining the credibility of sources) is also integral to data literacy, they are are expected to correlate positively. However, as conscientiousness is expected to be more stable over time, opposing to data literacy, they should not correlate to highly positive (i.e. correlation should be small) (cf. Table 1). 

## Aim of the Study    
The aim was to derive a comprehensive definition of data literacy based on existing approaches and to develop a questionnaire for self-rated data literacy with citizens being the target population. Thus the research question of this study is: 

"Does the proposed set of items effectively capture the latent factor structure of self-rated data literacy, and can the created scale be considered a reliable and valid measure of this construct?"

*H1: The training-data will support the suggested latent factor structure and the proposed measurement model.*  
*H2: The latent factor structure of the initial analysis will be supported by a different sample.*  
*H3: A moderate to high positive correlation with information behavior related self-efficacy (SWE-IV-16) [@behm2018] is expected.*  
*H4: A moderate positive correlation with self-perceived competence in using information and communication technology (ICT-SC25) [@schauffel2021] is expected.*  
*H5: A small positive correlation with need for cognition (NFC-K) [@beißert2015] is expected.*  
*H6: A small positive correlation with openness to new experiences (BFI-10) [@rammstedt2014] is expected.*  
*H7: A small positive correlation with conscientiousness (BFI-10) [@rammstedt2014] is expected.* 
