---
output:
  pdf_document: default
  html_document: default
---
# Appendix

\begin{table}
\begin{flushleft}
\caption{The selected item pool}
\begin{tabular}{lp{17cm}}
\toprule
Factor & Item \\
\midrule
1 & Bei der Auswertung von Grafiken bin ich in der Lage, Widersprüche zu erkennen. \\
1 & Ich erkenne, ob die Interpretationen Anderer zu den vorliegenden Daten passen. \\
1 & Ich kenne unterschiedliche Arten von Grafiken. \\
1 & Ich kann die zentrale These eines wissenschaftlichen Textes erkennen.\\
2 & Wenn Ich die Glaubwürdigkeit von Informationen beurteile, berücksichtige ich den Ruf der Quelle.\\
2 & Ich kenne Merkmale zur Bewertung von Datenqualität.\\
2 & Ich überprüfe die Qualifikation von Autor*innen, bevor ich mich auf die Informationen verlasse.\\
2 & Ich erkenne, wenn Daten schlechte Qualität haben.\\
3 &  Ich beschäftige mich mit Informationen, die meine Ansichten in Frage stellen.\\
3 &  Ich kann schnell und ohne Schwierigkeiten Informationen in Datenbanken finden.\\
3 &  Ich bevorzuge datengestützte Informationen, wenn ich mir eine Meinung bilde.\\
3 &  Ich kann neue Informationen in meinen Wissensstand integrieren.\\
4 &  Ich kann Ergebnisse in Streudiagrammen darstellen.\\
4 &  Ich kann Daten in Grafiken so präsentieren, dass sie für verschiedene Zielgruppen verständlich sind.\\
4 &  Ich kann aus verschiedenen Darstellungsformen, die am besten geeignete auswählen.\\
4 &  Ich kann mit Programmen Grafiken erstellen, um Ergebnisse zu präsentieren.\\
5 &  Ich bin in der Lage, einfache Datenbanken zu verwalten.\\
5 &  Ich kann Datensätze mit einfachen statistischen Methoden analysieren.\\
5 &  Wenn ich mit umfangreichen Datensätzen konfrontiert werde, kann ich daraus Erkenntnisse gewinnen.\\
5 &  Wenn ich Daten analysiere, achte ich auf ein systematisches Vorgehen.\\

\bottomrule
\end{tabular}

\bigskip
\small\textit{Note}. The items selected by the algorithm in German.
\end{flushleft}
\end{table}


\begin{table}[!htbp]
\centering
\rotatebox{90}{%
\begin{minipage}{\textheight}
\caption{Correlations of Residuals}
\scriptsize % This makes the font smaller
\begin{tabular}{lcccccccccccccccccccc}
\hline
\textbf{Item} & \textbf{F1F6} & \textbf{F1F8} & \textbf{F1F11} & \textbf{F1F14} & \textbf{F2F2} & \textbf{F2F6} & \textbf{F2F15} & \textbf{F2F20} & \textbf{F3F2} & \textbf{F3F4} & \textbf{F3F6} & \textbf{F3F9} & \textbf{F4F1} & \textbf{F4F3} & \textbf{F4F6} & \textbf{F4F8} & \textbf{F5F3} & \textbf{F5F4} & \textbf{F5F8}  \\ 
\hline
F1F6    & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F8    & -0.342 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F11   & -0.118 & 0.497 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F14   & 0.231  & -0.287 & -0.010 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F2    & 0.225  & 0.115  & 0.127  & -0.203 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F6    & -0.396 & 0.141  & 0.363  & 0.010  & -0.078 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F15   & -0.444 & 0.258  & 0.174  & -0.041 & -0.264 & 0.160  & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F20   & -0.015 & -0.193 & -0.269 & 0.223  & -0.349 & -0.029 & -0.208 & 1.000 &       &       &       &       &       &       &       &       &       &       &       \\
F3F2    & 0.314  & -0.144 & -0.043 & 0.005  & -0.002 & -0.403 & -0.170 & 0.307  & 1.000 &       &       &       &       &       &       &       &       &       &       \\
F3F4    & 0.127  & 0.040  & 0.153  & 0.089  & 0.253  & -0.266 & -0.357 & -0.092 & 0.008  & 1.000 &       &       &       &       &       &       &       &       &       \\
F3F6    & 0.223  & 0.017  & -0.106 & 0.296  & 0.135  & -0.447 & 0.332  & 0.063  & 0.079  & 0.177  & 1.000 &       &       &       &       &       &       &       &       \\
F3F9    & 0.117  & -0.037 & -0.169 & 0.409  & -0.206 & -0.284 & -0.073 & 0.246  & 0.324  & 0.239  & 0.066  & 1.000 &       &       &       &       &       &       &       &       \\
F4F1    & -0.030 & 0.026  & -0.345 & -0.153 & -0.282 & -0.053 & 0.001  & 0.064  & -0.051 & -0.300 & -0.237 & 0.154  & 1.000 &       &       &       &       &       &       &       \\
F4F3    & -0.079 & -0.381 & -0.184 & 0.439  & -0.208 & 0.170  & -0.273 & 0.591  & 0.215  & 0.154  & -0.239 & 0.398  & -0.214 & 1.000 &       &       &       &       &       &       \\
F4F6    & 0.004  & 0.397  & -0.102 & -0.234 & 0.146  & -0.199 & 0.322  & -0.080 & 0.175  & -0.168 & -0.005 & 0.095  & 0.128  & -0.057 & 1.000 &       &       &       &       &       \\
F4F8    & 0.164  & -0.038 & -0.079 & 0.256  & -0.021 & 0.005  & -0.061 & -0.035 & 0.086  & -0.146 & 0.136  & -0.161 & -0.221 & -0.171 & -0.129 & 1.000 &       &       &       &       \\
F5F3    & 0.461  & -0.275 & -0.141 & 0.259  & 0.065  & -0.448 & -0.248 & -0.397 & -0.159 & 0.150  & -0.012 & -0.007 & 0.169  & -0.253 & 0.105  & 0.165  & 1.000 &       &       &       \\
F5F4    & -0.085 & 0.089  & -0.192 & 0.052  & -0.203 & 0.003  & -0.417 & 0.110  & 0.130  & -0.005 & -0.312 & 0.291  & 0.398  & 0.115  & -0.136 & -0.051 & -0.032 & 1.000 &       &       \\
F5F8    & 0.017  & -0.330 & -0.193 & -0.111 & 0.043  & -0.396 & -0.149 & -0.095 & 0.253  & 0.055  & -0.189 & 0.179  & 0.049  & 0.146  & 0.205  & -0.184 & 0.334  & 0.247  & 1.000 &       \\
F5F18   & 0.076  & 0.138  & 0.136  & 0.118  & -0.094 & -0.245 & -0.009 & -0.075 & 0.224  & 0.010  & 0.045  & 0.308  & -0.217 & -0.181 & 0.069  & 0.468  & 0.264  & -0.028 & 0.032  & 1.000 \\
\hline

\end{tabular}
\par % Ensures separation of the table and note

\small Note. The table displays the lower half of the correlation matrix of the items residuals from the training sample.
\end{minipage}%
}
\end{table}


\begin{table}[!htbp]
\centering
\rotatebox{90}{%
\begin{minipage}{\textheight}
\caption{Correlations of Residuals}
\scriptsize % This makes the font smaller
\begin{tabular}{lcccccccccccccccccccc}
\hline
\textbf{Item} & \textbf{F1F6} & \textbf{F1F8} & \textbf{F1F11} & \textbf{F1F14} & \textbf{F2F2} & \textbf{F2F6} & \textbf{F2F15} & \textbf{F2F20} & \textbf{F3F2} & \textbf{F3F4} & \textbf{F3F6} & \textbf{F3F9} & \textbf{F4F1} & \textbf{F4F3} & \textbf{F4F6} & \textbf{F4F8} & \textbf{F5F3} & \textbf{F5F4} & \textbf{F5F8} \\ 
\hline
F1F6     & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F8     & 0.235 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F11    & 0.264 & 0.124 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F1F14    & -0.352 & -0.083 & -0.010 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F2     & -0.056 & -0.278 & 0.045 & 0.061 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F6     & 0.005 & 0.091 & 0.266 & 0.224 & -0.568 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F15    & -0.207 & -0.310 & -0.028 & 0.031 & 0.346 & -0.491 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       &       \\
F2F20    & 0.032 & 0.067 & 0.411 & 0.103 & -0.033 & 0.120 & -0.020 & 1.000 &       &       &       &       &       &       &       &       &       &       &       &       \\
F3F2     & -0.192 & -0.306 & -0.480 & 0.176 & 0.280 & -0.306 & 0.068 & -0.107 & 1.000 &       &       &       &       &       &       &       &       &       &       &       \\
F3F4     & -0.172 & -0.096 & -0.262 & 0.107 & -0.140 & 0.145 & 0.297 & -0.465 & 0.056 & 1.000 &       &       &       &       &       &       &       &       &       &       \\
F3F6     & 0.188 & 0.306 & 0.177 & -0.031 & 0.128 & -0.103 & 0.083 & -0.026 & -0.089 & -0.387 & 1.000 &       &       &       &       &       &       &       &       &       \\
F3F9     & 0.192 & -0.198 & 0.250 & 0.143 & 0.145 & 0.107 & -0.117 & 0.043 & -0.163 & -0.317 & 0.492 & 1.000 &       &       &       &       &       &       &       &       \\
F4F1     & 0.110 & 0.329 & -0.152 & 0.038 & -0.287 & 0.451 & -0.323 & 0.186 & -0.368 & 0.108 & -0.155 & -0.161 & 1.000 &       &       &       &       &       &       &       \\
F4F3     & 0.057 & 0.032 & 0.427 & 0.112 & 0.077 & 0.156 & -0.237 & 0.456 & -0.524 & -0.292 & 0.010 & 0.282 & 0.262 & 1.000 &       &       &       &       &       &       \\
F4F6     & 0.017 & -0.065 & 0.188 & 0.272 & 0.366 & 0.102 & -0.352 & 0.132 & -0.052 & 0.053 & -0.257 & 0.207 & 0.093 & 0.506 & 1.000 &       &       &       &       &       \\
F4F8     & 0.091 & 0.105 & 0.256 & 0.361 & -0.429 & 0.713 & -0.308 & 0.112 & -0.396 & 0.159 & -0.114 & -0.007 & 0.461 & 0.106 & 0.092 & 1.000 &       &       &       &       \\
F5F3     & 0.092 & -0.036 & -0.462 & -0.286 & 0.037 & -0.002 & 0.106 & -0.102 & 0.017 & 0.337 & -0.293 & -0.230 & 0.244 & -0.245 & 0.046 & -0.231 & 1.000 &       &       &       \\
F5F4     & -0.089 & -0.128 & 0.293 & -0.222 & -0.329 & 0.420 & -0.225 & 0.336 & -0.486 & 0.078 & -0.265 & -0.016 & 0.293 & 0.641 & 0.255 & 0.163 & 0.043 & 1.000 &       &       \\
F5F8     & 0.278 & 0.011 & -0.143 & -0.185 & 0.275 & -0.429 & 0.071 & 0.036 & 0.229 & -0.178 & 0.321 & 0.272 & -0.064 & 0.074 & 0.156 & -0.497 & 0.016 & -0.053 & 1.000 &       \\
F5F18    & 0.312 & 0.225 & 0.078 & -0.384 & 0.119 & 0.132 & -0.284 & 0.281 & -0.166 & -0.100 & -0.103 & -0.152 & 0.466 & 0.346 & 0.249 & 0.179 & 0.173 & 0.288 & -0.038 & 1.000 \\
\hline

\end{tabular}
\par % Ensures separation of the table and note

\small Note. The table displays the lower half of the correlation matrix of the items residuals from the test sample.
\end{minipage}%
}
\end{table}



\begin{table}
\centering
\rotatebox{90}{ %
\begin{minipage}{\textheight} % Ensures caption is properly associated with the rotated content
\caption{Item Correlations With Confidence Intervals}
\scriptsize
\begin{tabular}{lccccccccccccccccccc}
\hline
\textbf{Var}  &  \textbf{1} & \textbf{2} & \textbf{3} & \textbf{4} & \textbf{5} & \textbf{6} & \textbf{7} & \textbf{8} & \textbf{9} & \textbf{10} & \textbf{11} & \textbf{12} & \textbf{13} & \textbf{14} & \textbf{15} & \textbf{16} & \textbf{17} & \textbf{18} & \textbf{19} \\
\hline
1. F1F6 &  & &  &  &  & &  &  &  &  &  &  &  &  &  &  &  &  &  \\
2. F1F8 & .60** &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
&  [ .21, .82] &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
3. F1F11 & .41 & .42 &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
                & [-.03, .72] & [-.03, .73] &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
4. F1F14 & .30 & .25 & .24 &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
              & [-.16, .66] & [-.21, .63] & [-.22, .62] &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
5. F2F2 & -.27 & -.25 & -.25 & -.03 &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
               & [-.64, .20] & [-.62, .22] & [-.62, .22] & [-.46, .42] &  &  &  &  &  &  &  &  &  &  &  &  &  \\
6. F2F6 & -.07 & -.01 & .00 & -.05 & -.16 &  &  &  &  &  &  &  &  &  &  &  &  &  \\
               & [-.50, .38] & [-.45, .43] & [-.44, .44] & [-.48, .40] & [-.56, .30] &  &  &  &  &  &  &  &  &  &  &  &  \\
7. F2F15 & -.16 & -.02 & -.11 & -.42 & .09 & .27 &  &  &  &  &  &  &  &  &  &  &  &  \\
               & [-.56, .30] & [-.46, .43] & [-.53, .35] & [-.73, .03] & [-.37, .51] & [-.20, .63] &  &  &  &  &  &  &  &  &  &  &  &  \\
8. F2F20 & -.01 & .13 & .06 & .08 & -.01 & .60** & .10 &  &  &  &  &  &  &  &  &  &  &  \\
               & [-.45, .44] & [-.34, .54] & [-.39, .49] & [-.38, .50] & [-.45, .43] & [.21, .82] & [-.36, .52] &  &  &  &  &  &  &  &  &  &  \\
9. F3F2 & -.48* & -.34 & -.28 & -.33 & -.01 & -.14 & .10 & .18 &  &  &  &  &  &  &  &  &  &  \\
               & [-.76, -.05] & [-.68, .12] & [-.65, .18] & [-.67, .13] & [-.45, .43] & [-.55, .33] & [-.36, .52] & [-.29, .57] &  &  &  &  &  &  &  &  &  &  \\
10. F3F4 & -.03 & -.18 & -.20 & .01 & .01 & .12 & -.04 & .30 & .07 &  &  &  &  &  &  &  &  &  \\
                & [-.47, .42] & [-.58, .28] & [-.59, .27] & [-.43, .45] & [-.44, .45] & [-.34, .53] & [-.47, .41] & [-.16, .66] & [-.38, .50] &  &  &  &  &  &  &  &  &  \\
11. F3F6 & .08 & -.15 & -.02 & -.43 & .04 & -.15 & -.12 & -.31 & -.04 & .04 &  &  &  &  &  &  &  &  \\
                & [-.37, .51] & [-.56, .31] & [-.46, .42] & [-.73, .02] & [-.41, .48] & [-.55, .32] & [-.53, .34] & [-.66, .16] & [-.48, .41] & [-.41, .48] &  &  &  &  &  &  &  &  \\
12. F3F9 & -.14 & -.17 & .05 & .07 & .15 & .07 & -.07 & .15 & -.00 & .45* & -.10 &  &  &  &  &  &  &  &  \\
                & [-.55, .33] & [-.57, .30] & [-.40, .49] & [-.38, .50] & [-.31, .56] & [-.39, .50] & [-.50, .38] & [-.31, .56] & [-.45, .44] & [.00, .74] & [-.52, .36] &  &  &  &  &  &  &  &  \\
13. F4F1 & .07 & .01 & .04 & .26 & -.65** & .18 & -.33 & -.02 & -.32 & -.18 & -.23 & -.10 &  &  &  &  &  &  \\
               & [-.39, .50] & [-.44, .45] & [-.41, .47] & [-.21, .63] & [-.85, -.29] & [-.28, .58] & [-.67, .13] & [-.46, .42] & [-.67, .15] & [-.58, .28] & [-.61, .24] & [-.52, .36] &  &  &  &  &  &  \\
14. F4F3 & .16 & .17 & .11 & .27 & -.46* & .04 & -.35 & .09 & -.26 & -.07 & -.29 & .05 & .53* &  &  &  &  &  \\
               & [-.30, .57] & [-.30, .57] & [-.35, .53] & [-.19, .64] & [-.75, -.02] & [-.41, .47] & [-.69, .11] & [-.37, .51] & [-.63, .21] & [-.50, .39] & [-.65, .18] & [-.40, .48] & [.11, .79] &  &  &  &  &  \\
15. F4F6 & .14 & .13 & .29 & .31 & -.38 & .03 & -.24 & .12 & -.25 & .13 & -.24 & .11 & .34 & .64** &  &  &  &  \\
                & [-.32, .55] & [-.33, .54] & [-.18, .65] & [-.16, .66] & [-.70, .08] & [-.41, .47] & [-.62, .23] & [-.34, .53] & [-.63, .21] & [-.33, .54] & [-.62, .22] & [-.35, .52] & [-.12, .68] & [.27, .84] &  &  &  &  \\
16. F4F8 & .31 & .13 & .39 & .26 & -.47* & .07 & -.39 & -.01 & -.42 & -.09 & -.24 & -.06 & .54* & .67** & .53* &  &  &  \\
               & [-.15, .66] & [-.33, .54] & [-.06, .71] & [-.21, .63] & [-.76, -.04] & [-.39, .49] & [-.71, .07] & [-.45, .43] & [-.73, .02] & [-.52, .36] & [-.62, .22] & [-.49, .39] & [.12, .79] & [.33, .86] & [.12, .79] &  &  &  \\
17. F5F3 & .25 & .03 & -.15 & .03 & -.35 & -.11 & -.45* & -.23 & -.15 & .17 & .03 & -.28 & .26 & .40 & .24 & .49* & \\
               & [-.22, .62] & [-.42, .46] & [-.56, .31] & [-.42, .46] & [-.69, .10] & [-.53, .35] & [-.74, -.00] & [-.61, .24] & [-.56, .31] & [-.29, .57] & [-.42, .47] & [-.64, .19] & [-.21, .63] & [-.05, .72] & [-.22, .62] & [.06, .77] &  \\
18. F5F4 & .12 & -.23 & .13 & .31 & -.53* & .01 & -.41 & -.07 & -.07 & -.10 & -.30 & .01 & .61** & .63** & .49* & .69** & .44 &  \\
               & [-.34, .53] & [-.61, .23] & [-.33, .54] & [-.15, .66] & [-.79, -.11] & [-.43, .45] & [-.72, .03] & [-.50, .39] & [-.50, .38] & [-.52, .35] & [-.65, .17] & [-.43, .45] & [.22, .83] & [.26, .84] & [.05, .76] & [.35, .87] & [-.01, .74] &  \\
19. F5F8 & .17 & .13 & .15 & .35 & -.42 & -.21 & -.29 & -.03 & .02 & -.27 & -.24 & -.16 & .38 & .60** & .39 & .55* & .43 & .63** \\
                & [-.29, .57] & [-.34, .54] & [-.31, .56] & [-.11, .69] & [-.73, .02] & [-.60, .25] & [-.65, .17] & [-.46, .42] & [-.43, .46] & [-.62, .22] & [-.57, .30] & [-.07, .71] & [.21, .82] & [-.06, .71] & [ .15, .80] & [-.01, .73] & [ .25, .84] &  \\
20. F5F18 & .41 & .17 & .47* & .34 & -.45* & -.01 & -.26 & .15 & -.20 & .12 & -.22 & .01 & .32 & .43 & .47* & .62** & .38 & .60** \\
                & [-.05, .72] & [-.30, .57] & [.03, .75] & [-.12, .68] & [-.74, -.00] & [-.45, .43] & [-.63, .21] & [-.32, .55] & [-.59, .27] & [-.34, .53] & [-.61, .24] & [-.43, .45] & [-.14, .67] & [ .24, .83] & [-.08, .70] & [.21, .82] & [ .27, .84] &  \\
\hline
\end{tabular}
\par % Ensures separation of the table and note

\small Note. The table displays the lower half of the correlation matrix of the items from the whole sample. M and SD are used to represent mean and standard deviation, respectively. Values in square brackets indicate the 95% confidence interval. The confidence interval is a plausible range of population correlations that could have caused the sample correlation (Cumming, 2014). * indicates p < .05. ** indicates p < .01.
\end{minipage}%
}
\end{table}