---
title: "Decision-log"
author: "Leonie Hagitte"
date: "2024-07-20"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Decisions in the process of the Masters Thesis

Due to the large number of decisions made in the thesis, documenting all of them within the main text was neither appropriate nor feasible. Therefore, a separate decision log in the appendix documents most of these decisions.

Decision-making can be based on various grounds: evidence-based, pragmatic, arbitrary, or other reasons (e.g., personal values, political issues). Firstly, a decision is considered evidence-based if it can be clearly supported by empirical evidence or literature. Secondly, decisions might be made for pragmatic reasons, such as time constraints. Thirdly, arbitrary reasons come into play when neither evidence nor pragmatism applies, but a decision is still necessary. Although this reason does not directly aid in choosing an option, it highlights the frequency of decisions made without substantive or pragmatic grounds, potentially leading to random choices. Lastly, other reasons for decisions, which are unpredictable but significant, should also be recorded.
In some instances, multiple grounds may influence a decision. In such cases, the relevance of each reason can be ranked if possible.
This list is not exhaustive, but meant to incorporate and clarify as many decisions as possible.

## Background
Decision element: 
Result: Decision to create and use a self-rating questionnaire to assess data literacy among citizens as part of the study.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: Decision to compare different definitions and frameworks of data literacy across various subjects and professions.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: Decision to focus on citizens in data literacy research.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: Decision to describe data literacy not just as a capability or skill but as a competency or proficiency that includes motivation and personal predispositions.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: correlation expectations
Grounds: Primary - ;
         Secondary – 


## Methods
Decision element: 
Result: Decision to perform a literature review and conduct ten iterative cognitive interviews to refine survey items.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: Decision to treat the first 25 participants as a pilot group to identify potential issues with the survey.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: Decision to determine the design of the measurement model, specifically deciding on the number of items per factor for the final scale.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to create a parsimonious scale with four items per factor, balancing model fit and simplicity, while allowing for a real model fit to be assessed.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to recruit participants using personal and professional networks and various online platforms (e.g., Instagram, LinkedIn, WhatsApp, Telegram, and email).
Grounds: Primary - pragmatig;
         Secondary – 
         
Decision element: 
Result: Decision to conduct the study in German and ensure that participation is entirely voluntary without external incentives.
Grounds: Primary - empirical ;
         Secondary – pragmatic

Decision element: 
Result: Decision to conduct a priori power analysis using the ‘semPower’ package in R and consider estimates from similar studies to determine the necessary sample size.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to aim for an optimal sample size between 500 and 1000, based on power analysis results and literature.
Grounds: Primary - empirical;
         Secondary – 
         
Decision element: 
Result: Decision to include attention check questions in the survey, with participants who fail to correctly answer at least two of four questions being excluded from the analysis.
Grounds: Primary - empirical;
         Secondary – 
         
Decision element: 
Result: Decision to include specific criteria for participants (e.g., legal age)
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: document demographics such as gender distribution, average age, education level, employment status, and student status.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to use the reproducibility workflow proposed by @Peikert2021, combining Docker and renv to create a portable and reproducible environment for analysis.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to use the reproducibil r chunks from Brandmaier and Peikert 2024
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to preregister the study at Zenodo with DOI:10.5281/zenodo.11196495 to ensure transparency and reproducibility.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to utilize a cross-sectional online survey to examine a sample from the general population.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to randomize survey questions for each participant to minimize order effects and response biases.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: Decision to randomly select half of the questions from each factor of the data literacy questionnaire for each participant, leaving the other half as planned missings to shorten the assessment.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: Decision to use a questionnaire with 71 items to measure data literacy, where each participant answers 38 randomly selected items.
Grounds: Primary - pragmatic ;
         Secondary – arbitrairy
         
Decision element: 
Result: Decision to utilize a five-point Likert scale (1 = "strongly disagree" to 5 = "strongly agree") with a “don’t know” option for responses.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to use the SWE-IV-16 (Behm, 2018) as a proxy for information literacy, measuring self-efficacy in information behavior with 16 statements.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to use the NFC-K (Beißert et al., 2015) to assess Need for Cognition through four items, measured with a seven-point scale.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to employ the ICT-SC25 (Schauffel et al., 2021) for assessing self-perceived competence in ICT, using five general items from a 25-item scale.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to use the BFI-10 (Rammstedt et al., 2014) to measure personality traits of openness and conscientiousness, averaging responses from two items per dimension.
Grounds: Primary - ;
         Secondary – 

## Analysis
Decision element: 
Result: Decision to analyze data quality by using multiple mechanisms to identify careless or inattentive response patterns and outliers.
Grounds: Primary - ;
         Secondary – 

Decision element: 
Result: Decision to use algorithm-based item selection to choose the most relevant items from the initial pool, aiming for efficiency and objectivity.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to optimize the data literacy self-rating scale based on model fit criteria (RMSEA, SRMR, CFI) and composite reliability (McDonald's ω) as well as variability in item difficulty.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to use the genetic algorithm from 'Stuart' to reduce the item pool, leveraging evolutionary principles of selection, crossover, mutation, and survival of the fittest to find a near-optimal solution.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to define the criteria for optimization (model fit and composite reliability) within the fitness function used in the genetic algorithm.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision (gene function setup).
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision HOW to split the sample into two subsets: training data and test data, using the ‘holdout' function in ‘stuart’. 
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Deciding on the size.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision HOW to conduct k-fold cross-validation (k=3) on the training data using the ‘kfold’ function in ‘stuart’.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Deciding on the fold number
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to use the test data for evaluating the final model's performance and latent correlations with convergent measures.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision HOW to validate the measurement models for invariance between the training and test datasets using the ‘crossvalidate’ and ‘max.invariance' functions in ‘stuart’.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result: Decision to require invariance of the measurement models as a condition for claiming successful scale validation.
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result:
Grounds: Primary - ;
         Secondary – 
         
Decision element: 
Result:
Grounds: Primary - ;
         Secondary – 


## Statistical Analyses
Decision element: 
Result:
Grounds: Primary - ;
         Secondary – 

Decision element: Standard Deviation for nu in the objective function
Result: 1.62
Grounds: Primary - other reasons, I investigated it with a theoretical model;
         Secondary – pragmatic reason, other models would have been feasable as well,
         but I just chose one that would be fine, without assessing whether it would be the best possible, due to time               constraints.